version: '2'

services:
  redis_master_job:
     image: redis:3
     ports:
       - '6379:6379'
   redis_slave_job:
     image: redis:3
     command: redis-server --port 6380 --slaveof "${EXTERNAL_HOST}" 6379 --slave-announce-ip "${EXTERNAL_HOST}"
     ports:
       - '6380:6380'
   sentinel:
     build: ./sentinel
     ports:
       - '26379:26379'
     environment:
       - SENTINEL_NAME_JOB=jobqueue02
       - HOST_IP="${EXTERNAL_HOST}"
